### PR TITLE
Update2.0v

### PR DESCRIPTION
**Pull request by bshifaw**
- Updating workflow to 2.0v
  - Changes to the inputs included with the dna seq single sample references struct:
  - Removed 'fingerprint_genotypes_file' and 'fingerprint_genotypes_index' from bundle and made these optional pipeline inputs
  - Removed 'haplotype_scatter_count' and 'break_bands_at_multiples_of' from bundle and added these to a separate 'VariantCallingScatterSettings' struct
  - Added 'haplotype_database_file' to the references bundle as a non-optional file
  - Renamed GermlineSingleSampleReferences to DNASeqSingleSampleReferences
  - Updated shared tasks to support the new TargetedSomaticSingleSample pipeline
- Removed import urls and left in the local directory paths, because Dockstore/Terra can now handle relative import paths.
- Increased the disk multiplier in SortSam task from the original dsde-pipeline from 3.25 to 6.25, in order for the workflow to run on Terra. Reason for this change is due to the difference in PAPI version being used in Terra vs prod.

### CODE REVIEW

**Comment by rogerdettloff** [comment]
@bshifaw I've been trying to run this workflow in Terra (the version available from the docstore tagged as v.1.1.0).  It keeps failing during the SortSam task with Error Code 10.   Which I assumed to be due to low memory or low disk space.  While troubleshooting that issue, I found this PR, where you have apparently already fixed the  problem with b54aa9a.  Thank you.  I wonder when this will be available to run from within Terra?  Or perhaps you have a development build that I can help test.

**Comment by bshifaw** [comment]
Hi @rogerdettloff,

I'm currently conducting tests on Terra to confirm it works, once complete i'll merge the changes and create a new release by the end of the week. You can run this fixed version of the workflow in Terra now by selecting version `update2.0V` in your workflow tab of your workspace.

**Comment by rogerdettloff** [comment]
@bshifaw 
I ran this branch on my data file, like this:
image
The SortSam step still fails with the following message:
**"Job Failed with Error Code 10 for a machine where Preemptible is set to false"**

Here's the last bit of the workflow_..._.log:
```
2020-06-04 02:23:26,864 INFO  - a989e7c6-6841-423f-bc92-7765d50c5e65-SubWorkflowActor-SubWorkflow-UnmappedBamToAlignedBam:-1:1 [UUID(a989e7c6)]: Starting UnmappedBamToAlignedBam.SortSampleBam
2020-06-04 02:23:28,369 INFO  - PipelinesApiAsyncBackendJobExecutionActor [UUID(a989e7c6)UnmappedBamToAlignedBam.SortSampleBam:NA:3]: `java -Dsamjdk.compression_level=2 -Xms4000m -jar /usr/gitc/picard.jar \
  SortSam \
  INPUT=/cromwell_root/fc-6d2c33e9-c093-4c0f-b9f6-4c0b044ad94f/2decab76-0ddd-4604-a4e7-75ce9d880887/ExomeGermlineSingleSample/027e97a5-5232-44f7-b8d7-8ed3fdea72cb/call-UnmappedBamToAlignedBam/UnmappedBamToAlignedBam/a989e7c6-6841-423f-bc92-7765d50c5e65/call-MarkDuplicates/attempt-2/P0.GRCh38DH.exome.aligned.unsorted.duplicates_marked.bam \
  OUTPUT=P0.GRCh38DH.exome.aligned.duplicate_marked.sorted.bam \
  SORT_ORDER="coordinate" \
  CREATE_INDEX=true \
  CREATE_MD5_FILE=true \
  MAX_RECORDS_IN_RAM=300000`
2020-06-04 02:23:28,860 INFO  - PipelinesApiAsyncBackendJobExecutionActor [UUID(a989e7c6)UnmappedBamToAlignedBam.SortSampleBam:NA:3]: To comply with GCE custom machine requirements, memory was adjusted from 5000 MB to 5120 MB
2020-06-04 02:23:31,494 INFO  - PipelinesApiAsyncBackendJobExecutionActor [UUID(a989e7c6)UnmappedBamToAlignedBam.SortSampleBam:NA:3]: job id: projects/sequence-analysis/operations/4311596629505266330
2020-06-04 02:23:31,959 INFO  - PipelinesApiAsyncBackendJobExecutionActor [UUID(a989e7c6)UnmappedBamToAlignedBam.SortSampleBam:NA:3]: Status change from - to Initializing
2020-06-04 02:24:19,682 INFO  - PipelinesApiAsyncBackendJobExecutionActor [UUID(a989e7c6)UnmappedBamToAlignedBam.SortSampleBam:NA:3]: Status change from Initializing to Running
2020-06-04 03:22:56,719 INFO  - PipelinesApiAsyncBackendJobExecutionActor [UUID(a989e7c6)UnmappedBamToAlignedBam.SortSampleBam:NA:3]: Status change from Running to Preempted
2020-06-04 03:23:01,622 INFO  - a989e7c6-6841-423f-bc92-7765d50c5e65-SubWorkflowActor-SubWorkflow-UnmappedBamToAlignedBam:-1:1 [UUID(a989e7c6)]: Retrying job execution for UnmappedBamToAlignedBam.SortSampleBam:NA:4
2020-06-04 03:23:01,914 INFO  - a989e7c6-6841-423f-bc92-7765d50c5e65-SubWorkflowActor-SubWorkflow-UnmappedBamToAlignedBam:-1:1 [UUID(a989e7c6)]: Starting UnmappedBamToAlignedBam.SortSampleBam
2020-06-04 03:23:04,339 INFO  - PipelinesApiAsyncBackendJobExecutionActor [UUID(a989e7c6)UnmappedBamToAlignedBam.SortSampleBam:NA:4]: `java -Dsamjdk.compression_level=2 -Xms4000m -jar /usr/gitc/picard.jar \
  SortSam \
  INPUT=/cromwell_root/fc-6d2c33e9-c093-4c0f-b9f6-4c0b044ad94f/2decab76-0ddd-4604-a4e7-75ce9d880887/ExomeGermlineSingleSample/027e97a5-5232-44f7-b8d7-8ed3fdea72cb/call-UnmappedBamToAlignedBam/UnmappedBamToAlignedBam/a989e7c6-6841-423f-bc92-7765d50c5e65/call-MarkDuplicates/attempt-2/P0.GRCh38DH.exome.aligned.unsorted.duplicates_marked.bam \
  OUTPUT=P0.GRCh38DH.exome.aligned.duplicate_marked.sorted.bam \
  SORT_ORDER="coordinate" \
  CREATE_INDEX=true \
  CREATE_MD5_FILE=true \
  MAX_RECORDS_IN_RAM=300000`
2020-06-04 03:23:04,859 INFO  - PipelinesApiAsyncBackendJobExecutionActor [UUID(a989e7c6)UnmappedBamToAlignedBam.SortSampleBam:NA:4]: To comply with GCE custom machine requirements, memory was adjusted from 5000 MB to 5120 MB
2020-06-04 03:23:06,495 INFO  - PipelinesApiAsyncBackendJobExecutionActor [UUID(a989e7c6)UnmappedBamToAlignedBam.SortSampleBam:NA:4]: job id: projects/sequence-analysis/operations/5605733234399367687
2020-06-04 03:23:06,612 INFO  - PipelinesApiAsyncBackendJobExecutionActor [UUID(a989e7c6)UnmappedBamToAlignedBam.SortSampleBam:NA:4]: Status change from - to Initializing
2020-06-04 03:23:24,456 INFO  - PipelinesApiAsyncBackendJobExecutionActor [UUID(a989e7c6)UnmappedBamToAlignedBam.SortSampleBam:NA:4]: Status change from Initializing to Running
2020-06-04 04:21:08,193 INFO  - PipelinesApiAsyncBackendJobExecutionActor [UUID(a989e7c6)UnmappedBamToAlignedBam.SortSampleBam:NA:4]: Status change from Running to Failed
2020-06-04 04:21:08,251 INFO  - PipelinesApiAsyncBackendJobExecutionActor [UUID(a989e7c6)UnmappedBamToAlignedBam.SortSampleBam:NA:4]: Job Failed with Error Code 10 for a machine where Preemptible is set to false
2020-06-04 04:21:09,824 INFO  - $e [UUID(027e97a5)]: Copying workflow logs from /cromwell-workflow-logs/workflow.027e97a5-5232-44f7-b8d7-8ed3fdea72cb.log to gs://fc-6d2c33e9-c093-4c0f-b9f6-4c0b044ad94f/2decab76-0ddd-4604-a4e7-75ce9d880887/workflow.logs/workflow.027e97a5-5232-44f7-b8d7-8ed3fdea72cb.log
```
Here's the interesting bit of the "SortSampleBam.log":
```
03:28:46.558 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/usr/gitc/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Thu Jun 04 03:28:46 UTC 2020] SortSam INPUT=/cromwell_root/fc-6d2c33e9-c093-4c0f-b9f6-4c0b044ad94f/2decab76-0ddd-4604-a4e7-75ce9d880887/ExomeGermlineSingleSample/027e97a5-5232-44f7-b8d7-8ed3fdea72cb/call-UnmappedBamToAlignedBam/UnmappedBamToAlignedBam/a989e7c6-6841-423f-bc92-7765d50c5e65/call-MarkDuplicates/attempt-2/P0.GRCh38DH.exome.aligned.unsorted.duplicates_marked.bam OUTPUT=P0.GRCh38DH.exome.aligned.duplicate_marked.sorted.bam SORT_ORDER=coordinate MAX_RECORDS_IN_RAM=300000 CREATE_INDEX=true CREATE_MD5_FILE=true    VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=2 GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Thu Jun 04 03:28:46 UTC 2020] Executing as root@9c79c9212ec0 on Linux 4.19.112+ amd64; OpenJDK 64-Bit Server VM 1.8.0_222-8u222-b10-1~deb9u1-b10; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.20.4-SNAPSHOT
INFO	2020-06-04 03:30:13	SortSam	Read    10,000,000 records.  Elapsed time: 00:01:25s.  Time for last 10,000,000:   85s.  Last read position: chr6:38,842,753
INFO	2020-06-04 03:31:35	SortSam	Read    20,000,000 records.  Elapsed time: 00:02:48s.  Time for last 10,000,000:   82s.  Last read position: chr3:100,655,066
INFO	2020-06-04 03:33:01	SortSam	Read    30,000,000 records.  Elapsed time: 00:04:14s.  Time for last 10,000,000:   86s.  Last read position: chr17:50,675,801
INFO	2020-06-04 03:34:25	SortSam	Read    40,000,000 records.  Elapsed time: 00:05:38s.  Time for last 10,000,000:   83s.  Last read position: chr7:100,578,074
INFO	2020-06-04 03:35:42	SortSam	Read    50,000,000 records.  Elapsed time: 00:06:55s.  Time for last 10,000,000:   77s.  Last read position: chr8:43,158,884
INFO	2020-06-04 03:37:00	SortSam	Read    60,000,000 records.  Elapsed time: 00:08:13s.  Time for last 10,000,000:   77s.  Last read position: chr4:78,045,326
INFO	2020-06-04 03:38:20	SortSam	Read    70,000,000 records.  Elapsed time: 00:09:33s.  Time for last 10,000,000:   80s.  Last read position: chr19:16,577,536
INFO	2020-06-04 03:39:42	SortSam	Read    80,000,000 records.  Elapsed time: 00:10:55s.  Time for last 10,000,000:   81s.  Last read position: chr19:48,106,403
INFO	2020-06-04 03:43:36	SortSam	Finished reading inputs, merging and writing to output now.
INFO	2020-06-04 03:43:38	SortingCollection	Creating merging iterator from 299 files
```
The BAM file that I'm analyzing does not seem unusual. It was created by running the " PairedFastQsToUnmappedBAM" workflow:
image

Please let me know if there is something more I can do to help troubleshoot this issue.

**Comment by bshifaw** [comment]
Hi @rogerdettloff 
This question would be best placed in the [Terra forum ](https://support.terra.bio/hc/en-us/community/topics/360001603491-Featured-Workspaces). This updated version of the workflow passed on Terra, so it might be related to your data.

**Pull request merged**
